name: graphfex_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - ipykernel
  - nbformat
  - graphviz
  - python-graphviz
  - git-lfs
  - pip